# Generated by Django 5.0.6 on 2024-06-19 13:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("knbase", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="OutboundLink",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("created", models.DateTimeField(auto_created=True)),
                ("domain", models.CharField(max_length=2000)),
                ("raw_url", models.CharField(max_length=2000)),
                ("url", models.CharField(max_length=2000)),
                ("outbound_url", models.CharField(max_length=2000)),
            ],
            options={
                "unique_together": {("url", "outbound_url")},
            },
        ),
    ]
