name: Python package

on: [push]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4
      - name: Install a specific version and validate the checksum
        uses: eifinger/setup-rye@v3
        with:
          version: '0.34.0'
          enable-cache: true
      - name: Build
        run: make build
      - name: Lint
        run: make lint
      - name: Test
        run: make test